spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.zthlugetibaquiixubfd
    password: szY6t-WrN,g2wxH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: X3pL9vW2zN5mQ8rT1uB4yD7gJ0hK3nM6pS9vV2yB5eH8kJ1nM4pQ7sT0wW3zZ6aC9
  expiration: 86400000
server:
  port: 7000