spring:
  datasource:
    url: jdbc:h2:mem:logisticsdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true                         # access H2 UI at /h2-console
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop                 # creates tables on start, drops on stop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 7000
