spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000

# Eureka settings for dev (inherits from logistics.yml)
eureka:
  server:
    # Can override here if needed
